// PRODUCT.md §15, grouped for the footer.
export const SOURCES: { group: string; links: [string, string][] }[] = [
  {
    group: 'Assignment & Upstox',
    links: [
      ['Assignment / API overview', 'https://upstox.com/developer/api-documentation/api-overview/'],
      ['Every Upstox doc page (llms.txt)', 'https://upstox.com/developer/api-documentation/llms.txt'],
      ['Upstox tax ecosystem: Tax P&L, Quicko / ClearTax', 'https://upstox.com/market-talk/5-things-traders-and-investors-need-to-know-about-itr-filing/'],
      ['Upstox web Reports: verified from the owner’s screenshot, Funds page, 19 Sep 2026', ''],
    ],
  },
  {
    group: 'What exists today',
    links: [
      ['Upstox tax-loss harvesting launch (Mar 2025): downloadable list of loss-making stocks, FIFO', 'https://community.upstox.com/t/turn-portfolio-losses-into-tax-savings-time-is-running-out/8628'],
      ['Upstox in-app tax-loss harvesting (21 Mar 2026): tax summary, stocks to sell, buy-back nudge after T+1', 'https://community.upstox.com/t/tax-loss-harvesting-is-now-easier-on-upstox/14700'],
      ['LinkedIn post on Upstox tax-loss harvesting', 'https://www.linkedin.com/posts/mehveshibrahim_taxlossharvesting-personalfinance-tax-activity-7443926823245357056-VAMj/'],
      ['Upstox tax-loss harvesting page', 'https://account.upstox.com/reports/tax-loss-harvesting'],
      ['Upstox Tax P&L is a download', 'https://tax2win.in/guide/file-itr-for-upstox'],
      ['Zerodha tax reports (Jul 2026)', 'https://zerodha.com/z-connect/featured/tax-reports-to-simplify-filing-your-taxes'],
      ['Zerodha holdings breakdown (age per lot)', 'https://support.zerodha.com/category/console/reports/taxation/articles/capital-gain-applicability-on-holdings'],
      ['Zerodha tax-loss harvesting', 'https://zerodha.com/z-connect/taxation-for-traders/tax-loss-harvesting'],
      ['Groww tax-loss harvesting (May 2025)', 'https://groww.in/updates/updates-from-groww-tax-loss-harvesting-intraday-oco-bonds-and-lots-more'],
      ['Groww “Capital Gains in Redeem” (MF only)', 'https://groww.in/updates/introducing-capital-gains-in-redeem-on-groww'],
      ['Kuvera gain harvesting (MF only; units redeemable within the limit)', 'https://kuvera.in/feature/tax-harvesting'],
    ],
  },
  {
    group: 'Why it matters',
    links: [
      ['First-time investors struggle with LTCG reporting (Upstox News, 29 Jul 2026)', 'https://upstox.com/news/personal-finance/tax/filing-itr-before-july-31-tax-experts-say-first-time-investors-are-struggling-with-ltcg-reporting/article-197763/'],
      ['Individuals sold 70% of IPO shares within a year (SEBI)', 'https://www.businesstoday.in/markets/story/54-ipo-shares-allotted-to-investors-sold-within-a-week-sebi-study-444054-2024-09-02'],
      ['Intraday loss-makers spent an extra 57% of losses on costs (SEBI, FY23)', 'https://www.business-standard.com/amp/markets/news/over-70-intra-day-traders-incur-losses-during-fy23-reveals-sebi-study-124072401110_1.html'],
      ['13 crore investors vs 1.08 crore active (May 2026)', 'https://www.nooreshtech.co.in/2026/09/india-has-23-crore-demat-accounts-but-how-many-investors-actually-show-up.html'],
      ['Tax-loss / gain harvesting explained', 'https://www.share.market/buzz/learn/tax-loss-harvesting/'],
    ],
  },
  {
    group: 'Tax rules (§9)',
    links: [
      ['Income-tax Act, 2025 (as amended by FA 2026)', 'https://www.incometaxindia.gov.in/documents/d/guest/income_tax_act_2025_as_amended_by_fa_act_2026-pdf'],
      ['New Act + section mapping, R7', 'https://taxguru.in/income-tax/capital-gains-income-tax-act-2025-tax-period-2026-27.html'],
      ['R1, R2: Budget 2026, rates unchanged', 'https://www.angelone.in/news/taxation/union-budget-2026-ltcg-tax-unchanged-at-12-5-stt-on-commodity-futures-hiked'],
      ['R3, R4: cess, surcharge cap', 'https://tax2win.in/guide/short-term-capital-gain-under-section-111a'],
      ['R5: debt MF, Sec 50AA', 'https://cleartax.in/s/section-50aa-income-tax-act'],
      ['R6: gold / international funds', 'https://www.finnovate.in/learn/blog/debt-fund-taxation-india-fair-treatment'],
      ['R8: FIFO (CBDT Circular 768)', 'https://incometaxindia.gov.in/communications/circular/910110000000000355.htm'],
      ['R9: grandfathering', 'https://taxharvestlab.com/blog/grandfathering-clause-ltcg'],
      ['R10: unused basic exemption', 'https://upstox.com/news/personal-finance/tax/can-i-adjust-stcg-ltcg-against-the-basic-exemption-limit-under-both-old-and-new-tax-regimes/article-165394/'],
      ['R11: Section 156 rebate', 'https://cleartax.in/s/section-156-income-tax-act-2025'],
      ['R12: buyback', 'https://upstox.com/news/personal-finance/tax/fm-nirmala-sitharaman-changes-share-buybacks-income-tax-rules-investors-to-pay-capital-gains-tax/article-188702/'],
      ['R13: same-day = intraday', 'https://1finance.co.in/blog/tax-loss-harvesting-march-31-save-capital-gains-from-stocks-mutual-funds/'],
      ['R14, R15: intraday / F&O losses', 'https://www.caclubindia.com/articles/fo-intraday-and-share-trading-losses-how-to-claim-maximum-tax-benefit-through-itr3-setoff-and-carry-forward-55793.asp'],
      ['R16: STT hike Apr 2026', 'https://www.bajajamc.com/knowledge-centre/union-budget-2026'],
      ['R17: ICAI turnover', 'https://taxsocial.pro/article/fno-intraday-trading-taxation-ay-2026-27-itr-3-audit-44ad'],
      ['R18: slabs', 'https://cleartax.in/s/income-tax-slabs'],
      ['R19: ITR forms', 'https://zerodha.com/varsity/chapter/itr-forms/'],
      ['R20: 31 Aug for ITR-3', 'https://www.jmfinancialservices.in/blogs-and-articles/itr-3-and-itr-4-filing-deadline-extended-to-31st-august-2026'],
      ['R21: advance tax, no 234C on capital gains', 'https://taxguru.in/income-tax/section-234c-interest-relaxed-dividend-income-capital-gain.html'],
      ['R22: FMV = highest price on 31 Jan 2018', 'https://taxguru.in/income-tax/tax-ltcg-listed-shares-securities-wef-01-04-2018-section-1038.html'],
      ['R23: stamp duty in cost, STT not deductible', 'https://github.com/codereverser/casparser'],
      ['R24: MF stamp duty 0.005% (HDFC MF FAQ)', 'https://files.hdfcfund.com/s3fs-public/2020-07/FAQs%20on%20Stamp%20Duty.pdf'],
      ['R24: stamp duty on MF investors (Groww)', 'https://groww.in/blog/stamp-duty-on-mutual-fund-investors'],
      ['R25: ELSS lock-in per instalment', 'https://cleartax.in/s/elss-lock-in-period'],
      ['MF lots: each SIP instalment taxed separately', 'https://www.dspim.com/knowledge-hub/personal-finance-guide/tax-on-sip-investments-how-each-instalment-is-taxed'],
      ['MF lots: FIFO for equity mutual funds (Upstox News)', 'https://upstox.com/news/personal-finance/tax/how-capital-gains-tax-on-equity-mutual-funds-is-calculated-using-the-fifo-method/article-185996/'],
      ['Historical NAVs: mfapi.in', 'https://www.mfapi.in/docs/'],
    ],
  },
]
